### ISSUE TITLE
Proposal to add poe

### ISSUE THREAD

**Issue by nat-n** [carlosperate/awesome-pyproject#32]
[Poe the Poet](https://github.com/nat-n/poethepoet) is a task runner that works well with poetry. 

Tasks are defined in the pyproject.toml

```toml
[tool.poe.tasks]
test = "pytest --cov=src"
```

and executed via a dedicated cli tool

```bash
poe test
```

I would make a PR to add it, but it's not obvious where a _task runner_ should go within the current organisation of projects.
